### ISSUE TITLE
Why do directly with the database? XenApi does the same thing, and easier to use

### ISSUE THREAD

**Issue by aquaminer** [Muqsit/XenForoPM#1]

**Comment by Muqsit** [comment]
Not everyone uses XenAPI.

**Comment by aquaminer** [comment]
@Muqsit good amendment) I wish you success with the plugin

**Comment by Muqsit** [comment]
@opkiler22789 thank you :)
Actually, it would be a pain if the user would have to set up XenAPI separately just because the plugin uses it.
